name: PC Virtual

on:
  workflow_dispatch:

jobs:
  pc-virtual:
    runs-on: ubuntu-latest

    steps:
      - name: Actualizar sistema
        run: |
          sudo apt update

      - name: Instalar escritorio y VNC
        run: |
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server dbus-x11

      - name: Configurar VNC
        run: |
          mkdir -p ~/.vnc

          # Contraseña VNC: 12345678
          echo "12345678" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          cat > ~/.vnc/xstartup <<'EOF'
          #!/bin/sh
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          startxfce4 &
          EOF

          chmod +x ~/.vnc/xstartup

          vncserver :1 \
            -geometry 1280x720 \
            -depth 24 \
            -localhost no \
            -rfbport 5901 \
            -PasswordFile ~/.vnc/passwd

      - name: Mantener PC virtual encendida
        run: |
          echo "PC virtual iniciada."
          echo "VNC: puerto 5901"
          echo "Contraseña: 12345678"
          sleep 21600
